import { Inter } from "next/font/google";
import Link from "next/link"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Codeart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <header className="flex justify-start gap-10 flex-col items-center p-5 absolute top-0 left-0 h-full z-10 bg-black">
          <img className="w-10" src="https://previews.123rf.com/images/sansakphoto/sansakphoto2304/sansakphoto230401459/203758987-astronauta-en-el-espacio-ultraterrestre-ilustraci%C3%B3n-para-su-dise%C3%B1o.jpg" alt="" />
          <nav className="flex">
            <ul className="flex flex-col gap-5 justify-center items-center">
              <li><Link href="cursehtml">cursehtml</Link></li>
              <li><Link href="cursecss">cursecss</Link></li>
              <li><Link href="cursejs">cursejs</Link></li>
            </ul>
          </nav>
        </header>
        
        {children}

        <footer className="absolute bottom-0 left-0 flex justify-center items-center p-2 w-full">
          <h1>este es el footer</h1>
        </footer>
      </body>
    </html>
  );
}
